In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
arr = np.array([3, -7, 1, 4, 2])

In [9]:
arr

array([ 3, -7,  1,  4,  2])

In [8]:
type(arr)

numpy.ndarray

In [10]:
sorted_indices = np.argsort(arr)

In [11]:
sorted_indices

array([1, 2, 4, 0, 3])

In [14]:
print("Indices for sorted array:", sorted_indices)

Indices for sorted array: [1 2 4 0 3]


In [16]:
print(arr[sorted_indices])

[-7  1  2  3  4]


In [17]:
result = np.where(arr > 1, arr, 0)

In [18]:
result

array([3, 0, 0, 4, 2])

In [19]:
abs_values = np.abs(arr)
abs_values

array([3, 7, 1, 4, 2])